version: '3'
services:
  kinesalite:
    build:
      context: ./kinesalite
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/local/src
    ports:
      - "4567:4567"
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./dynamodb/local/data:/data
    ports:
      - 8000:8000
  ddb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    links:
      - dynamodb
    ports:
      - 8001:8001

